### ISSUE TITLE
Microphone disable

### ISSUE THREAD

**Issue by iProGamer** [TheHolyWaffle/TeamSpeak-3-Java-API#277] opened 2018-07-14 13:28 UTC
How can I check if the user has microphone disabled?
I searched a lot about this but couldn't find it

**Comment by rogermb** [comment] 2018-07-14 16:08
I think `Client#isInputMuted` is what you're looking for 😃

**Comment by iProGamer** [comment] 2018-07-14 19:46
@rogermb This doesn't work
I think you didn't understand what is microphone disabled
This is a screenshot of it:
http://prntscr.com/k6hjjq

**Comment by rogermb** [comment] 2018-07-14 19:56
I'm pretty sure we're talking about the same thing, and `Client#isInputMuted` is working properly on my end.

Test code (not pretty, but it works):

```java
List<Client> clients;
do {
	clients = api.getClients();
	for (Client client : clients) {
		if (client.isRegularClient()) {
			System.out.println(client.getNickname() + ": " + client.isInputMuted());
		}
	}
	Thread.sleep(1000L);
} while (clients.size() > 1);
```

Result:

This
![image](https://user-images.githubusercontent.com/1472572/42727980-ae184e78-87b0-11e8-87ce-acbb35921ee3.png)
prints `rogermb: false`

---

This
![image](https://user-images.githubusercontent.com/1472572/42727973-8100a82c-87b0-11e8-9b96-5ebcd8976007.png)
prints `rogermb: true`

**Comment by rogermb** [comment] 2018-07-14 20:06
Oh, maybe you're talking about the microphone being deactivated due to being online on two servers at the same time, like this:

![image](https://user-images.githubusercontent.com/1472572/42728044-bab231fc-87b1-11e8-884f-9527a6c669c4.png)

In that case, I think you could use `Client#isInputHardware` (named after the "client_input_hardware" property, which isn't documented by TeamSpeak...). That property seems to be true if the microphone is activated and false if it isn't.

**Comment by rogermb** [comment] 2018-07-14 20:35
To learn about this API, you can take a look at some of the examples [here](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/master/example) or the JavaDoc [here](http://www.javadoc.io/doc/com.github.theholywaffle/teamspeak3-api/1.1.0). The classes you'll need the most often are [TS3Api](http://static.javadoc.io/com.github.theholywaffle/teamspeak3-api/1.1.0/com/github/theholywaffle/teamspeak3/TS3Api.html) and probably also the [Client](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/Client.java) and [ClientInfo](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/ClientInfo.java) classes.

If you understand the TS3 server query interface (some documentation [here](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf)), this API should hopefully be pretty intuitive to use.

If you're having any other issues, questions, or suggestions, feel free to also drop by our [Gitter channel](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) 😄

**Comment by iProGamer** [comment] 2018-07-14 21:06
Sorry for this but it's not working well, this returns false not only when the user has Microphone disabled but also when he has Microphone muted which I don't need.
This is what I mean: http://prntscr.com/k6ib3w I want to check if the user has microphone disabled (if he goes in 2 servers)

**Comment by rogermb** [comment] 2018-07-14 21:15
That's strange, `Client#isInputHardware` still returns true for me if I just mute my microphone (i.e. in the two pictures in my first response, `Client#isInputHardware` returns true).

If I disable my microphone and then mute it, `Client#isInputHardware` also still returns false, as you'd expect.

Can you describe the steps you're taking to get `Client#isInputHardware` to return false while the microphone is not disabled?

**Comment by iProGamer** [comment] 2018-07-14 21:37
Sorry for that I deleted the comment, I was wrong, It's now working fine
I have another question
Is it possible to use both getApi and getAsyncApi?
I want to use the async api to check for afk users every 5 seconds and move them to afk channel, and use the normal api for events
Is that a good way for doing it?

**Comment by rogermb** [comment] 2018-07-14 21:46
Sure, you can use both at the same time.

If you need to do that 5-second AFK check from something like a "tick" function that should complete in a fixed amount of time, using the async API is probably a good idea.

Alternatively, you could use a [ScheduledThreadPoolExecutor](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html) and its `scheduleAtFixedRate` function to make that AFK check run every five seconds. That executor has its own threads in which blocking for some time isn't an issue, so that way you could continue to use the simpler synchronous API :smiley:

**Comment by iProGamer** [comment] 2018-07-14 22:16
Thanks for the informative reply.
I have a problems with events that are not triggering
my main class:
``
public static void main(String[] args){

		TS3Config config = new TS3Config();
		config.setHost("localhost");
		config.setFloodRate(FloodRate.UNLIMITED);
		
		System.out.println("Connecting...");
		
		TS3Query query = new TS3Query(config);
		query.connect();
		
		api = query.getAsyncApi();
		api.login("serveradmin", "mypass");
		api.selectVirtualServerById(7);
		api.setNickname("Bot");
		query.getApi().addTS3Listeners(new EventListener());
	}
``
event listener class:
``
public class EventListener extends TS3EventAdapter{
	
	
	@Override
	public void onTextMessage(TextMessageEvent e){
		System.out.println(e.getMessage());
	}
	
	@Override
	public void onClientLeave(ClientLeaveEvent e){
		System.out.println("Left: " + e.getClientId());
	}

}
``
The bot is connecting perfectly but the events are not triggering cuz am not getting any debug messages in console.

Also I can't send private messages to the bot, I get this error:
``
<01:34:28> You are attempting to chat with a ServerQuery client. Please note that text messages will only be received if the ServerQuery is registered for private text messages events with "servernotifyregister event=textprivate".
<01:34:29> This ServerQuery client did not register for the private text message event using "servernotifyregister event=textprivate". The text message was not received.
<01:43:15> This ServerQuery client did not register for the private text message event using "servernotifyregister event=textprivate". The text message was not received.
``
Can you help me to solve that?

**Comment by rogermb** [comment] 2018-07-14 22:20
I think I've already spotted the problem:

You also need to call `TS3Api#RegisterEvent(TS3EventType)` or `TS3Api#RegisterAllEvents()` to tell the server that you want to receive event notifications :smiley:

**Comment by iProGamer** [comment] 2018-07-14 22:36
Events are working now and I can but the TextMessageEvent triggers only if you write in the channel where the bot is but I want to trigger the bot private chat

**Comment by rogermb** [comment] 2018-07-14 22:42
If you're using `TS3Api#RegisterAllEvents()`, private messages should work "out of the box". If you're registering all the events separately, make sure you're also calling `RegisterEvent` with `TS3EventType.TEXT_PRIVATE`.

If that wasn't the cause of your issue, it may just be the old TS3 client chat bug. Sometimes private chats stop working if your chat partner dis- and reconnects. Please try closing the chat tab you're using to send private messages to the query and start a new private chat tab.

**Comment by iProGamer** [comment] 2018-07-14 23:03
Thanks, it worked and yeah am using an old version of ts <3

**Comment by rogermb** [comment] 2018-07-14 23:06
Oh, I meant "old bug" as in "that bug has been in the client for so long and still hasn't been fixed", not "that bug has been fixed a long time ago" 😛

I'll go ahead and close this issue for now. If you have any other problems or questions, feel free to re-open the issue, or contact us over on [Gitter](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API). Thanks!

**Closed by rogermb** 2018-07-14 23:06 UTC
Labels: question
