### ISSUE TITLE
getServerGroupClients() causes NullPointerException

### ISSUE THREAD

**Issue by byfareska** [TheHolyWaffle/TeamSpeak-3-Java-API#193] opened 2017-05-17 07:37 UTC
getServerGroupClients() causes NullPointerException if servergroup is empty

**Comment by rogermb** [comment] 2017-05-17 08:17
Very interesting! I'll look into it either this evening or tomorrow.

Thanks for bringing this to my attention 😊

**Comment by rogermb** [comment] 2017-05-18 22:52
Quick progress update:

The problem has been located, but not yet fixed. I'll get that done in the next few days.
The bug was caused by the TS3 Server Query interface being inconsistent - which should come as no surprise to anyone who has ever worked with this interface.

In essence, we assumed that if a command successfully returns with an `error id=0 msg=ok`, then the server will have sent back some kind of response beforehand.
This was a natural assumption to make, as the TS3 server always tries to avoid sending nothing, either by also sending some more information along or by returning with a different error code, e.g. the `empty result set` error, ID 1281.

However, the `servergroupclientlist` command seems to work differently in that regard. It just doesn't send a response containing data and still responds with `error id=0 msg=ok` if the server group did not contain any clients.

This causes the `response` variable of the command to be `null` when we try to access the data sent back by the server, which causes this `NullPointerException`.

Unfortunately, I don't think there's a good way to work around this issue. Sorry about that 😞

**Comment by rogermb** [comment] 2018-04-08 21:48
Fixed in 8b51fbc7f374697c61ad5911fa500c60eed9d84a, just now made it into the v1.1.0 beta release.

**Closed by rogermb** 2018-04-08 21:48 UTC
Labels: bug
