### ISSUE TITLE
Virus found in teamspeak3-javadoc.jar

### ISSUE THREAD

**Issue by PhillTV** [TheHolyWaffle/TeamSpeak-3-Java-API#370] opened 2020-07-19 12:12 UTC
So i wanted to download the javadoc because i dont know which of the three files work. And then Chrome activated its Virus scanner and i cannot download the javadoc anymore. What is in this .jar?
![image](https://user-images.githubusercontent.com/50775241/87874377-a9a51800-c9c9-11ea-92cf-bc7d26db38bd.png)

**Comment by rogermb** [comment] 2020-07-19 12:55
Hmm, that's strange. On [VirusTotal](https://www.virustotal.com/gui/file/546167b180c7519b0678864a45c560d9a6ea4467557eaa01df44ab2af0da9e88/detection), none of the antivirus engines detect the Javadoc jar as malicious. After all, it's just a zip archive containing HTML files...

We had a similar issue a while back caused by a false-positive by Windows defender, #267, which we were able to get resolved. However, I'm also using Windows defender, and I can't reproduce this issue myself - I can download the JAR file just fine and it shows up as clean if I scan it.

Could it be that you're somehow using an outdated version of Windows defender? Perhaps you're developing in an old Windows VM or something like that?

**Comment by PhillTV** [comment] 2020-07-19 14:08
Im not using a VM. I use the newest Windows version and i thought i disabled Windows defender.

**Comment by Tumbledore** [comment] 2020-07-19 16:28
Google Chrome blocks by default all executionable Files. Here a Support Link: https://support.google.com/chrome/answer/99020?hl=en
As it seems it isnt correctly downloaded i think That is the answer you are looking for. 
Sry for the grammar im on the phone ;)

**Comment by Tumbledore** [comment] 2020-07-19 16:36
as im now on PC i can maybe explain it a bit better.
as mentioned above Google Chrome (https://support.google.com/chrome/answer/99020?hl=en) always blocks executable Files if it isnt deactivated in the Settings or it isnt a Popular File.
If it is some Issue with Windows Defender it will be Downloaded but you cant Access it properly :)

**Comment by rogermb** [comment] 2020-07-22 00:08
Still nothing on VirusTotal, still not able to replicate this on my machine. This seems to be an issue with your machine or with Google Chrome. I'll go ahead and close this issue. If you're able to replicate this on a different machine or have more information on this issue @PhillTV, feel free to re-open this issue.

**Closed by rogermb** 2020-07-22 00:08 UTC
