### ISSUE TITLE
In Chat there's a delay

### ISSUE THREAD

**Issue by hashtagMrice** [TheHolyWaffle/TeamSpeak-3-Java-API#316] opened 2019-03-14 23:00 UTC
Hey, i coded a querybot with holywaffleapi 1.2.0 with dependencies and theres a delay ~8-12 seconds. I wonder why and can't get a solution.

**Comment by FLOODY88** [comment] 2019-03-22 13:40
Hi @hashtagMrice, may you provide MCV example of your code so one can look into your issue.

**Comment by Galileon-venta** [comment] 2019-03-24 22:58
Hey, i've experienced a similar problem probably caused by the following line:
`load.api.sendPrivateMessage(c.getId(),"Als ich programmiert wurde, dachte sich mein Entwickler: Artikel13 ist die dümmste Erfindung der Welt");`

Just // it out and performance was back up again...

**Comment by rogermb** [comment] 2019-03-24 23:02
Hi again @hashtagMrice, sorry for taking so long to respond. I had a really busy week.

As @FLOODY88 mentioned, seeing your code would be really helpful. It would also be awesome if you could turn on communications logging by calling `TS3Config#setEnableCommunicationsLogging(true)` and upload the resulting log messages here.

@Galileon-venta: "sendPrivateMessage" should be just as fast as any other command. Are you sure you're not just calling that method very often? And if you really need to call it very often: consider whitelisting your query IP on your TS3 server so you can turn on the `FloodRate.UNLIMITED` flood rate.

**Comment by Galileon-venta** [comment] 2019-03-24 23:08
@rogermb Floodrate and Whitelist already done...

In this Codepiece I'm calling sendPrivateMessage 2 Times in a row...
In Other Cases I got no trouble with sending 10 Messages or Pokes in a Row...

**Comment by rogermb** [comment] 2019-03-24 23:19
@Galileon-venta I don't know if you care enough about this issue to want to troubleshoot it, but if you do: it would be awesome if you could also send me your code and maybe even a communications log with that `sendPrivateMessage` call in it 😄

**Comment by Galileon-venta** [comment] 2019-03-24 23:49
Haha activating Full Log of PrivateMessages got me to my mistake 🤣 🤣 🤣 

Forgot to cover that every Chat Message send by Query is also handled by onTextMessage(Event e)...
So with every Message I've called 2 New Messages 🤦‍♂️ 
Reducing it to One fixed the Input Lag, because sceduling 1 for 1 is better than 2 for 2; its a k^n mistake...

I know how to fix it but I need the ID, which defines the Current Query Connection... is there anything like api/query.getId() or do I need to go with a Workaround via find Id by Username? 
If workaround is needed, add a api/query.getId() method to feature wishlist maybe?

**Comment by Galileon-venta** [comment] 2019-03-24 23:55
Ok meh Brain is slow at 1 o Clock in the Night...

Now I've put this into the first line of my onTextMessage(TextMessageEvent e) Eventlistener

`if(e.getInvokerId() == e.getTargetClientId()) return;`

👍 Fixed from my site...
I believe @hashtagMrice got the same Mistake...

**Comment by rogermb** [comment] 2019-03-25 00:04
Just for completeness's sake:

> is there anything like api/query.getId()

Yes! `TS3Api#whoAmI()` (named after the TS3 server query command 😄)

Also, if you have a `Client` or `ClientInfo` object, there are `isRegularClient()` and `isServerQueryClient()` methods that you can use. It's probably a good idea not to respond to any messages sent by server queries 😃

**Comment by Galileon-venta** [comment] 2019-03-25 00:07
In my Case the Bot goes for:
Any Message that doesnt Equal a Command from a User in Group X,Y,Z,... gets a BotVersion Message and some Funny Text 🤣

**Comment by hashtagMrice** [comment] 2019-03-25 09:38
@Galileon-venton my problem was that I’ve forget to put Floodrate.UNLIMITED in my code

**Comment by rogermb** [comment] 2019-03-25 12:30
Ah, alright. I guess I can close this issue, then 😃

**Closed by rogermb** 2019-03-25 12:30 UTC
Labels: question
