### ISSUE TITLE
Ist it possible to add the Event onNickNameChange?

### ISSUE THREAD

**Issue by Bixilon** [TheHolyWaffle/TeamSpeak-3-Java-API#255] opened 2018-03-15 17:11 UTC
Is this possible? 
Or does it exists alredy?

Thanks:)

**Comment by rogermb** [comment] 2018-03-15 17:14
Quick answer: Nope. We don't control the server query interface. We just let you access the data the TS3 server sends you.

Longer answer: Exact duplicate of #222.

**Closed by rogermb** 2018-03-15 17:14 UTC
Labels: duplicate, enhancement, invalid

**Comment by Bixilon** [comment] 2018-03-15 17:16
Okay. So I should use the TeamSpeak 3 SDK?

**Comment by rogermb** [comment] 2018-03-15 17:22
Uhm, this really depends on what you want to do. I thought the TS3 SDK was more of a custom voice chat solution for people to integrate into their own programs / games / whatever, and not just a way to "customize" a TS3 server. If nickname changes are the only "custom" functionality you need, using the SDK feels way over the top.

But I really don't know much about the SDK, so take all of that with a grain of salt.

If you just need to know when a client changed their nickname, couldn't you just go with a polling approach? I.e. send a `clientlist` command (`TS3Api#getClients`) to the server every 0.5 seconds or so and check which clients have changed their name.

**Comment by Bixilon** [comment] 2018-03-15 17:27
Yes. The SDK ist Made for sth. Like Voicr Changes. I also dont know much about it, but I could try IT with Userlist...I will try IT. Thanks
