### ISSUE TITLE
Command whoami was not answered in time.

### ISSUE THREAD

**Issue by robingenz** [TheHolyWaffle/TeamSpeak-3-Java-API#56] opened 2015-08-19 10:41 UTC
I wrote a bot for my TS3 server with the aid of this API (using the latest version). Unfortunately, the bot stopped working after a few hours.
Eclipse stated the following errors:

Quellcode:

```
[2015-08-19 05:23:16.226] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:24:13.427] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:24:54.731] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:25:24.537] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:25:45.457] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:27:05.736] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:27:40.187] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:28:25.802] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:29:04.861] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:29:48.444] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:30:24.972] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:30:56.959] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:31:34.193] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:32:08.505] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:33:17.209] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:34:14.566] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:35:09.354] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:35:50.669] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:37:16.662] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:38:00.100] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:38:48.177] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:39:15.655] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:39:24.745] [SEVERE] Command clientinfo was not answered in time.
[2015-08-19 05:40:22.120] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:41:28.145] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:42:02.504] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:43:10.602] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:43:44.876] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:44:41.985] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:45:09.403] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:45:48.287] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:46:50.047] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:47:24.156] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:48:14.432] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:48:39.393] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:49:06.975] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:50:10.652] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:51:17.092] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:51:58.404] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:52:39.522] [SEVERE] Command clientinfo was not answered in time.
[2015-08-19 05:52:39.522] [SEVERE] Command whoami was not answered in time.
[2015-08-19 05:53:52.325] [SEVERE] Command whoami was not answered in time.
[2015-08-19 06:06:41.579] [SEVERE] Command clientinfo was not answered in time.
[2015-08-19 06:10:11.419] [SEVERE] Command clientinfo was not answered in time.
```

The log file of the API showed the following errors (they didn't cause the bot to stop working though):

```
[2015-08-19 04:53:31.616] [SEVERE] TS3 command error: {id=1281, msg=database empty result set}
[2015-08-19 04:53:57.270] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 04:57:29.073] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 04:57:56.457] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 05:01:01.964] [SEVERE] TS3 command error: {id=1281, msg=database empty result set}
[2015-08-19 05:01:55.578] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 05:05:55.014] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 05:08:28.235] [SEVERE] TS3 command error: {id=1281, msg=database empty result set}
[2015-08-19 05:09:54.569] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 05:12:02.538] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 05:13:54.869] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 05:15:54.650] [SEVERE] TS3 command error: {id=1281, msg=database empty result set}
[2015-08-19 05:17:55.180] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 05:21:05.503] [SEVERE] TS3 command error: {id=1281, msg=database empty result set}
[2015-08-19 05:21:12.590] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 05:21:25.642] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
[2015-08-19 05:21:53.852] [SEVERE] TS3 command error: {id=512, msg=invalid clientID}
```

I greatly appreciate your help.

**Comment by TheHolyWaffle** [comment] 2015-08-20 09:44
It happens when connection has been lost to the TS3 server. Unfortunately,
no automatic reconnection system is implemented yet.

2015-08-19 12:42 GMT+02:00 Red0head <notifications@github.com>:

**Comment by Red0head** [comment] 2015-08-20 10:09
Why should the bot lost the connection to the server when the server is still online? That's what i don't understand ^^
The server was all the time online and the bot lost the connection...

**Comment by TheHolyWaffle** [comment] 2015-08-20 16:15
The server must have gone offline at one point and restarted afterwards.Do
you host your own TS3 server? Or do you rent one?

2015-08-20 12:09 GMT+02:00 Red0head <notifications@github.com>:

**Comment by Firedroide** [comment] 2015-08-20 16:19
Hijacking this thread real quick.

@TheHolyWaffle, could you please catch up on what's going on over at [gitter](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API)? There's someone offering us a CI solution and he specifically wants to talk to you, as you're the owner of this repository.

**Comment by Red0head** [comment] 2015-08-20 16:58
I rent my own server and i log every downtime and i have users who were online for at least 8 hours and the bot lost the connection after 4 hours...

**Comment by Red0head** [comment] 2015-08-20 17:01
I deleted the "whoami-process" out of your API and now it works ^^ the bot is online since 16 hours ^^ which function has the command besides of saying "who i am"? Hahaha :D

**Comment by TheHolyWaffle** [comment] 2015-08-20 17:08
The whoami command is sent to keep the connection between you and the
server stable when you haven't send any commands for a long time.

2015-08-20 19:01 GMT+02:00 Red0head <notifications@github.com>:

**Comment by Red0head** [comment] 2015-08-20 17:19
What if i would let the whoami process out of your API and create a thread in my app who request a few information like the client number  any 5 minutes for example?

**Comment by Red0head** [comment] 2015-08-20 17:49
Btw very good api and nice support you saved me a lot of time :)

**Comment by TheHolyWaffle** [comment] 2015-08-20 19:34
What you just described is exactly what happens in the KeepAlive
functionality of the api.

Back to your issue, perhaps it must have been you who has lost connection
at one point to the server?

2015-08-20 19:49 GMT+02:00 Red0head <notifications@github.com>:

**Comment by Red0head** [comment] 2015-08-20 19:54
Alright i will check this. Would i have any cons when i would replace your "whoami" function with my thread(which send any 5 minutes a command)?

**Comment by Firedroide** [comment] 2015-08-20 21:46
Well, no, not really. "whoami" is just the command the TS3 API uses as a keepalive. Whether you substitute it or not doesn't really matter; once the connection is interrupted you'll stay disconnected.

**Comment by Red0head** [comment] 2015-08-20 23:34
okay i will run the bot and the teamspeak server now on the same server... there he shouldn't loss the connection ... ^^
I'll will get back soon

**Comment by Red0head** [comment] 2015-09-01 23:05
So i tested the bot now and the command whoami still "not answered in time". So what can i do now? I run the bot on the same server like the teamspeak ... He can't lose the connection (i mean it's the same server...) :/

**Comment by Kakifrucht** [comment] 2015-09-01 23:09
This shouldn't be happening, I use this API without any restarts for many months straight and there are no issues whatsoever. If you run locally try setting the FloodRate.UNLIMITED in the TS3Config object.

**Comment by Red0head** [comment] 2015-09-01 23:26
I know. I can't understand it why it didn't work for me. I still set the floodRate unlimited :/
What version did you used?

**Comment by Kakifrucht** [comment] 2015-09-01 23:29
I'm currently on the latest build, however the linked stable one worked fine aswell.

**Comment by Red0head** [comment] 2015-09-02 10:47
okay, i will try it again. But since yesterday i have a second problem. I didn't changed anything in my code and after ~5 hours of running the bot he stopped with this error message: "Socket Reader has stopped". What should I do?

**Comment by Firedroide** [comment] 2015-09-02 10:50
Was there a stack trace or anything else "unusual" in the log right before that?

**Comment by Firedroide** [comment] 2015-09-02 11:26
Something else I noticed is that the timestamps in your log are weird. Usually, the "whoami" commands should be exactly one minute apart.

```
[2015-09-02 13:14:42.349] > login serveradmin password
[2015-09-02 13:14:42.355] [login] < error id=0 msg=ok
[2015-09-02 13:15:42.610] > whoami
[2015-09-02 13:15:42.616] [whoami] < virtualserver_status=unknown virtualserver_unique_identifier virtualserver_port=0 virtualserver_id=0 client_id=0 client_channel_id=0 client_nickname client_database_id=1 client_login_name=serveradmin client_unique_identifier=serveradmin client_origin_server_id=0
[2015-09-02 13:15:42.618] [whoami] < error id=0 msg=ok
[2015-09-02 13:16:42.898] > whoami
[2015-09-02 13:16:42.904] [whoami] < virtualserver_status=unknown virtualserver_unique_identifier virtualserver_port=0 virtualserver_id=0 client_id=0 client_channel_id=0 client_nickname client_database_id=1 client_login_name=serveradmin client_unique_identifier=serveradmin client_origin_server_id=0
[2015-09-02 13:16:42.906] [whoami] < error id=0 msg=ok
[2015-09-02 13:17:43.169] > whoami
[2015-09-02 13:17:43.175] [whoami] < virtualserver_status=unknown virtualserver_unique_identifier virtualserver_port=0 virtualserver_id=0 client_id=0 client_channel_id=0 client_nickname client_database_id=1 client_login_name=serveradmin client_unique_identifier=serveradmin client_origin_server_id=0
[2015-09-02 13:17:43.177] [whoami] < error id=0 msg=ok
[2015-09-02 13:17:57.532] > clientlist -uid -away -voice -times -groups -info -icon -country
[2015-09-02 13:17:57.532] [clientlist] < error id=1024 msg=invalid\sserverID
[2015-09-02 13:17:57.533] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
[2015-09-02 13:18:57.789] > whoami
[2015-09-02 13:18:57.795] [whoami] < virtualserver_status=unknown virtualserver_unique_identifier virtualserver_port=0 virtualserver_id=0 client_id=0 client_channel_id=0 client_nickname client_database_id=1 client_login_name=serveradmin client_unique_identifier=serveradmin client_origin_server_id=0
[2015-09-02 13:18:57.795] [whoami] < error id=0 msg=ok
[2015-09-02 13:19:58.058] > whoami
[2015-09-02 13:19:58.065] [whoami] < virtualserver_status=unknown virtualserver_unique_identifier virtualserver_port=0 virtualserver_id=0 client_id=0 client_channel_id=0 client_nickname client_database_id=1 client_login_name=serveradmin client_unique_identifier=serveradmin client_origin_server_id=0
[2015-09-02 13:19:58.065] [whoami] < error id=0 msg=ok
```

In the code you sent us, there are segments where there's way more than 1 minute between the commands and other ones where there's less than 40 seconds in between.

So I wonder, are you running this API on a single-core machine or are you using this API in an "unconventional" way?

**Comment by Red0head** [comment] 2015-09-02 11:39
No nothing. I let the bot run on 3 different machines. My PC (i7 3770), my home server (amd processor 6 cores) and on a virtual server at my hosting provider.
On the two servers i use ubuntu 14.04.3 LTS with the "java-default" package and the "java jre8" package. I tested it on every machine with a local ts3 server.
I don't know what I'm doing wrong...

**Comment by Firedroide** [comment] 2015-09-02 11:51
Hmm... Have you tried increasing the command timeout via TS3Config.setCommandTimeout(millis)?
Might be worth a try.

By default, the timeout is set to 4 seconds, but it could happen that this is not long enough, especially if you're transmitting heaps of data. You maybe try setting it to something like 15 seconds / 15000 ms.

Usually, when a query is disconnected, the API currently seems to go rouge and starts sending the next keepalive command as soon as the previous one times out, i.e. after 4 seconds.

```
[2015-09-02 13:31:18.080] [SEVERE] Command whoami was not answered in time.
[2015-09-02 13:31:22.081] [SEVERE] Command whoami was not answered in time.
[2015-09-02 13:31:26.081] [SEVERE] Command whoami was not answered in time.
[2015-09-02 13:31:30.081] [SEVERE] Command whoami was not answered in time.
```

In your case, this is not what's happening, leading me to believe that maybe it's just occasional commands getting timed out. But I think I'm just as confused as you are ¯\\_(ツ)_/¯

**Comment by Red0head** [comment] 2015-09-02 12:08
Okay ty i will try this. I hope this will work ^^

**Comment by Firedroide** [comment] 2015-09-02 12:19
I'm going to let my instance run with this code

		while (!Thread.interrupted()) {
			long timeToSleep = (long) (Math.random() * TimeUnit.MINUTES.toMillis(15));
			Thread.sleep(timeToSleep);
			api.getClients();
		}

until midnight, so for almost 10 hours. So if there's an internal problem with the API, I should be able to catch it.

**Comment by Firedroide** [comment] 2015-09-02 21:25
Almost midnight now, everything's still working as intended.

If your project still doesn't work despite the longer command timeout, I'd have to look through your code to be able to help you further.

**Comment by Red0head** [comment] 2015-09-02 23:24
My bot runs now since 5 hours. Tomorrow i'll check how long the bot is running and post the result here.

**Comment by Kakifrucht** [comment] 2015-09-02 23:46
Since you are the only one having issues with this I suspect that it has something to do with your teamspeak server / CPU.
I run my bot on a digitalocean single core alongside an nginx instance and a teamspeak instance and never had any such problems. The API is as stable as can be.

**Comment by morrowwolf** [comment] 2017-01-09 21:52
So I have slight connectivity problems between my computer and teamspeak and generally it doesn't disconnect my client from the server but my bot must have a lower tolerance for dc times since it dies all the time.  Is there anyway to increase the tolerance?

**Comment by rogermb** [comment] 2017-01-09 22:05
TS3Config#setCommandTimeout(int milliseconds)

should be what you're looking for. Try increasing it to something like 15000.

If it doesn't just time out but actually disconnects, you could also look into enabling reconnecting (`setReconnectStrategy` and `setConnectionHandler`). Example [here](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/example/ReconnectExample.java).

**Comment by morrowwolf** [comment] 2017-01-09 22:14
Wow thanks for the extremely quick reply!  Will report back if I continue having problems.

**Comment by morrowwolf** [comment] 2017-01-10 01:47
[2017-01-09 19:22:15.349] [WARNING] Connection error occurred.
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at com.github.theholywaffle.teamspeak3.SocketReader.run(SocketReader.java:72)

[2017-01-09 19:22:15.349] [WARNING] SocketReader has stopped!
[2017-01-09 19:22:15.350] [SEVERE] [Connection] Disconnected from TS3 server

Yeah continues to happen.  I'm not sure if this is the right place to put this problem though.  It seems to just happen at random as well since it'll just not be doing anything and die.  I used an old version about a year ago and am still running on that code and it didn't use to do this so I'm unsure what it would be now.

**Comment by rogermb** [comment] 2017-01-10 02:07
That's just plain disconnecting, setting a longer timeout won't fix this.

You'll need to update to a newer version of the API and look into reconnecting :smile:

**Comment by morrowwolf** [comment] 2017-01-10 02:14
I'm on the newest API and adapted anything that didn't work any more to the newest version from before.  I'm wondering mainly if there's a way to fix this without having to have them reconnect constantly as it's fairly often that they break.  Would looking at my code help at all?  I don't want to spend too much of your time on my code if it turns out it's an internet problem.  The reconnecting solution just feels like a cop out.

**Comment by rogermb** [comment] 2017-01-10 02:21
To be honest, it does sound like a simple internet connection problem to me. This should never happen "fairly often" - I've ran this API over several days and never had any disconnects.

If you don't want to go for the reconnecting solution, you could also just run your server query application from the same machine you run your TS3 server on. That would probably be the quickest and cleanest fix.

To be honest, you should do that anyways - there's no guarantee that a command won't get sent a second time after reconnecting, which could always cause subtle problems. Moreover, everything sent over telnet is **unencrypted**. Everyone with physical access to the packets can simply read out the server query username & password combination.

Both of these problems are caused by one simple thing: Telnet is a bad and utterly broken protocol, and to be frank I have no idea why on earth TeamSpeak would choose such a protocol for a remote management interface. But we can't change it, so we'll just have to live with it.

**Comment by morrowwolf** [comment] 2017-01-10 02:25
Yeah I'll give running it on the same machine a try.  Thank you for all your time both with helping people and on this project.  You're really making people's lives easier as corny as that sounds.

**Comment by rogermb** [comment] 2017-01-10 14:20
Thank you for the kind words! I really appreciate it 😊

**Comment by fuadhamidli** [comment] 2018-03-02 09:20
Hi, 
I cant solve meterpreter problem in a following manner:

![image](https://user-images.githubusercontent.com/27348070/36891811-e120c07c-1e13-11e8-8875-fb69fa6acf51.png)
![image](https://user-images.githubusercontent.com/27348070/36891863-03d0b6ea-1e14-11e8-9cc5-6c1b9efd0be5.png)
Could anyone suggest anything about possible reasons?

**Comment by rogermb** [comment] 2018-03-02 09:30
Meterpreter? What on earth are you talking about, @fuadhamidli?

This project is a Java wrapper for the TeamSpeak server query interface. It is not in any way affiliated with Metasploit. You're not even targetting any TeamSpeak ports in your screenshot.

And while we're on the topic, why would you leave such a comment on a 2-year-old issue?

**Closed** 2019-02-03 00:58 UTC
