### ISSUE TITLE
ClientLeaveEvent not able to pull invoker name or nickname

### ISSUE THREAD

**Issue by Hink1** [TheHolyWaffle/TeamSpeak-3-Java-API#125] opened 2016-08-05 11:13 UTC
When getting the invoker nickname of a client on a disconnection I get returned a blank value.

Can the e.getClientNickname() method be added to the ClientLeaveEvent e listener?

**Comment by Firedroide** [comment] 2016-08-05 12:13
Duplicate of #65, see in particular [this comment](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/65#issuecomment-139353225).

**Closed by Firedroide** 2016-08-05 12:13 UTC
Labels: duplicate, question
