### ISSUE TITLE
SocketException when disconnecting

### ISSUE THREAD

**Issue by YvesW** [TheHolyWaffle/TeamSpeak-3-Java-API#129] opened 2016-08-19 08:05 UTC
Hey,

I like screwing around with some of the functions before trying to implement them in my TS bot. I just skinned the reconnect example, took 10 seconds to edit some stuff and ran it on a virtual machine, then disabled the LAN adapter to simulate a dc. This gave me a SocketException. I guess it should be caught by the api itself? The relevant console output:

```
[2016-08-19 09:36:12.467] [whoami] < error id=0 msg=ok
[2016-08-19 09:36:53.906] [WARNING] Connection error occurred.
java.net.SocketException: Software caused connection abort: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at java.io.BufferedReader.fill(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at com.github.theholywaffle.teamspeak3.SocketReader.run(SocketReader.java:74)

[2016-08-19 09:36:53.909] [WARNING] SocketReader has stopped!
[2016-08-19 09:36:53.910] [Connection] Disconnected from TS3 server
This is the on disconnect message
[2016-08-19 09:37:12.419] > whoami
```

Skinned recconectexample:
```
package ts3bot.reconnect.test;

import com.github.theholywaffle.teamspeak3.TS3Api;
import com.github.theholywaffle.teamspeak3.TS3Config;
import com.github.theholywaffle.teamspeak3.TS3Query;
import com.github.theholywaffle.teamspeak3.api.TextMessageTargetMode;
import com.github.theholywaffle.teamspeak3.api.event.TS3EventAdapter;
import com.github.theholywaffle.teamspeak3.api.event.TS3EventType;
import com.github.theholywaffle.teamspeak3.api.event.TextMessageEvent;
import com.github.theholywaffle.teamspeak3.api.reconnect.ConnectionHandler;
import com.github.theholywaffle.teamspeak3.api.reconnect.ReconnectStrategy;

import java.util.logging.Level;


public class TS3BotReconnectTest {


	private static volatile int clientId;

	public static void main(String[] args) {
		final TS3Config config = new TS3Config();
		config.setHost("11.11.11.11");
		config.setDebugLevel(Level.ALL);

		config.setReconnectStrategy(ReconnectStrategy.constantBackoff(285000));

		config.setConnectionHandler(new ConnectionHandler() {

			@Override
			public void onConnect(TS3Query ts3Query) {
				stuffThatNeedsToRunEveryTimeTheQueryConnects(ts3Query.getApi());
			}

			@Override
			public void onDisconnect(TS3Query ts3Query) {
				System.out.println("This is the on disconnect message");
			}
		});

		final TS3Query query = new TS3Query(config);
		query.connect();

		stuffThatOnlyEverNeedsToBeRunOnce(query.getApi());
	}

	private static void stuffThatNeedsToRunEveryTimeTheQueryConnects(TS3Api api) {
		api.login("serveradmin", "password");
		api.selectVirtualServerById(1);
		api.setNickname("TS3BotRecconectTest");


		api.registerEvent(TS3EventType.TEXT_SERVER, 0);


		clientId = api.whoAmI().getId();
                api.sendServerMessage(1,"TS3BotReconnectTest stuffThatNeedsToRunEveryTimeTheQueryConnects");

	}

	private static void stuffThatOnlyEverNeedsToBeRunOnce(final TS3Api api) {
		api.sendServerMessage(1,"TS3BotReconnectTest stuffThatOnlyEverNeedsToBeRunOnce");

		api.addTS3Listeners(new TS3EventAdapter() {

			@Override
			public void onTextMessage(TextMessageEvent e) {
				if (e.getTargetMode() == TextMessageTargetMode.SERVER && e.getInvokerId() != clientId) {
					api.sendServerMessage(1,"Hello " + e.getInvokerName() + "!");
				}
			}
		});
	}
}
```

**Comment by Firedroide** [comment] 2016-08-19 08:37
Heyo!

Those exceptions [are in fact caught](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/SocketReader.java#L72-L76), but we chose to print them to the log anyways because we don't want to hide any information from the user and it might turn out to be useful for debugging :smile:

**Comment by YvesW** [comment] 2016-08-19 09:33
My bad; I was retarded and only ctrl+f'd for "socket" instead of looking at the code.  :expressionless:

**Comment by YvesW** [comment] 2016-08-19 10:15
Well, since I'm here anyway, let's ask another stupid question. I still have to put time into looking into this, so you shouldn't invest too much time into it, but some directions would be great.

I have server group A with an add power of 50, so they can add people to server group B (needed add power group B = 50, add power group B = 0).
I want only channel admins (channel admin add power 5, channel admin needed add power 5) to be able to edit the respective channels that they're channel admin in + add people to the channel admin group for those channels only.
The problem with the above permission system is that people from server group A can make people (including themselves) channel admin while they aren't channel admin. I can't raise the needed add power for channel admins higher than 50, because that'd mean that the add power would need to be raised to the same number, and then channel admins could add people to server group B. AFAIK this can't be done by changing permissions, so I thougth I could use the API for this. Could you tell me if there's any way to catch the assignment of the channelgroup, aka the invoker + target user + target channel (haven't tested it, but I very much doubt it counts as a TextMessageEvent)? Finding out if the invoker is a channel admin, removing the channelgroup and deny people from changing their own channelgroup should be easy then.

**Comment by Firedroide** [comment] 2016-08-19 10:59
You can't really do that with the API. There's no event for it and even if there were one, you'd just create a giant mess of a patch that would barely work. You'll have to make it work with the TS3 permission system.

There's a good [overview of the system](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Permissions%20Guide.txt) on the TS3 servers that also discusses how permissions are overridden, negated, etc.

I've done some tests on my test server, and from what I can tell the following statement **isn't true**:

> I can't raise the needed add power for channel admins higher than 50, because that'd mean that the add power would need to be raised to the same number, and then channel admins could add people to server group B

My channel admin group has an `i_group_member_add_power` of 50 and my "Normal" server group has a `i_group_needed_member_add_power` of 40. Despite that, a Channel Admin was not able to change the server groups of a client.

I believe this is because channel and channel group permissions only get applied on a local channel basis, so just like a channel admin from channel A can't make a client a channel admin in channel B, they also can't change the server groups of any clients, no matter in which channel they are.

So to fix your issue, you'd probably just have to raise the `i_group_member_add_power` and the `i_group_needed_member_add_power` of your Channel Admin group to 60. (Alternatively, you could also lower both powers for server group A, which would have the same effect.)

**Comment by Firedroide** [comment] 2016-08-19 11:26
Okay, so that glitch was caused by the client not getting informed about the changing permissions. After re-joining the server, the channel admin *was* able to add clients to a server group. The client simply didn't display it as he still thought he didn't have enough power to make that change.

However, what *does* seem to work is setting `i_client_needed_permission_modify_power` for all server groups to a value higher than the Channel Admin group's `i_group_member_add_power`. To make sure that channel groups cannot overwrite the `i_client_needed_permission_modify_power` permission to a lower value, you should also set the skip flag on all of them.

Combining this with lowering server group B's `i_group_member_add_power` and `i_group_needed_member_add_power` (or raising those two values for channel admins) should yield the desired results.

**Comment by YvesW** [comment] 2016-08-19 22:16
Yeah, I also thougth that that would be very messy using the API. Using the permission system is indeed a lot better; I didn't think about using `i_client_needed_permission_modify_power`; great idea! It gives channel admins that aren't in group A still the option visually to add people to group B, but this returns `insufficient client permissions (failed on i_client_needed_permission_modify_power)` (which it should!). It'd of course be even nicer if it didn't give them the option in the GUI, but I guess that's not possible. Thanks for the solution!

**Comment by Firedroide** [comment] 2016-08-19 22:24
Yeah, that kinda annoyed me as well when I found out this little trick.

However, I think it's actually pretty impressive that it's possible to create two "separate" permission systems like that; with channel and server groups not being able to mess with each other :smile:

I'll go ahead and close this issue for now. If you have any other questions, feel free to re-open this issue, create a new issue or joins us over on the [Gitter chat channel](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API).

**Closed by Firedroide** 2016-08-19 22:24 UTC
Labels: question
