### ISSUE TITLE
ftinitupload Support

### ISSUE THREAD

**Issue by Hink1** [TheHolyWaffle/TeamSpeak-3-Java-API#131] opened 2016-08-22 08:58 UTC
Can the ftinitupload ServerQuery feature please be added?

**Comment by Firedroide** [comment] 2016-08-23 17:55
I'm working on it. The thing about the whole file upload stuff is that there's actually quite a bit to it, so it takes some time. It's also not as straightforward as the rest of the commands: there are quite a few edge cases and stuff that TS3 simply does completely differently for those commands. Example: Every command separates multiple return values with a `|`, but some file transfer commands put a newline there.

I'll try to finish the API as soon as possible, but I can't make any promises. I don't want to release an unfinished and buggy API.

Duplicate of #76, see also #115

**Comment by Firedroide** [comment] 2016-08-28 15:00
Added in 165739aa9b0d2255f3e48a4d0137ed7e6ad8c53a. Please let me know if the new API methods suit your demands.

As this is only a snapshot build, you'll have to [download it from the build repository](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/raw/mvn-repo/com/github/theholywaffle/teamspeak3-api/1.0.14-SNAPSHOT/teamspeak3-api-1.0.14-20160828.145049-8.jar). To get this build via Maven, you'll have to enable snapshot builds.

**Closed** 2017-02-27 21:29 UTC
Labels: duplicate, enhancement
