### ISSUE TITLE
Invalid Server ID?

### ISSUE THREAD

**Issue by Mauricius17** [TheHolyWaffle/TeamSpeak-3-Java-API#63] opened 2015-09-05 19:55 UTC
Hi,

I got this error! What does it mean? 

http://hastebin.com/kekapuyeko.tex

Maurice

**Comment by Firedroide** [comment] 2015-09-05 20:03
You need to select a virtual server first before you can get information about the clients present.  
Use `TS3Api#selectVirtualServerById` or `TS3Api#selectVirtualServerByPort` to do that.

If you're using an unlicensed TS3Server, you can only have 1 virtual server anyways and you can just call `api.selectVirtualServerById(1)`.

**Comment by Mauricius17** [comment] 2015-09-05 20:11
I did this! If i start the programm I used:

http://hastebin.com/xicaxitaci.avrasm

**Comment by Firedroide** [comment] 2015-09-05 20:23
Hmm...

Are you sure that this virtual server actually exists and is selected? The only way I've been able to get "invalid serverID" when running this command is when there's a problem selecting the virtual server.

Could you maybe post the whole log, please? That would help understanding what's actually going on.

**Comment by Kakifrucht** [comment] 2015-09-05 20:28
You could try connecting with selectVirtualServerByPort(yourPort).

**Comment by Mauricius17** [comment] 2015-09-05 20:57
Okay here is the code how I connect to the server:

http://hastebin.com/

And here is the code I am using :

http://hastebin.com/zelomolovo.coffee

**Comment by Mauricius17** [comment] 2015-09-05 20:58
@Kakifrucht Should I use the Query port? Or which port do you mean?

**Comment by Firedroide** [comment] 2015-09-05 20:59
I don't really need your code, I need the console log produced by the TS3 API :smile:

What is more, your first link is probably wrong.

**Comment by Mauricius17** [comment] 2015-09-05 21:01
@Firedroide I am sorry:) Here is the whole log : http://hastebin.com/ramovosusi.vbs

**Comment by Firedroide** [comment] 2015-09-05 21:03
```
[23:00:05] [[TeamSpeak-3-Java-API] SocketWriter/INFO]: [2015-09-05 23:00:05.168] > use port=10011
[23:00:05] [[TeamSpeak-3-Java-API] SocketReader/INFO]: [2015-09-05 23:00:05.230] [use] < error id=1024 msg=invalid\sserverID
[23:00:05] [[TeamSpeak-3-Java-API] SocketReader/INFO]: [2015-09-05 23:00:05.231] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
```

The issue is right there. You're not correctly selecting the virtual server. Port 10011 is your query port, not the voice port by which you can select a TS3 server.

Change this to 9987 or select the server by ID 1 and you should be fine.

**Comment by Firedroide** [comment] 2015-09-05 21:04
And if you're creating a Bukkit plugin, don't hardcode the ID. Give the users the option to customize the host and port, if you're not already doing that.

**Comment by Mauricius17** [comment] 2015-09-05 21:05
I am already doing that:

https://www.spigotmc.org/resources/teamspeak-verifier.8455/

**Comment by Mauricius17** [comment] 2015-09-05 21:05
I just want to update the plugin:)

**Comment by Kakifrucht** [comment] 2015-09-05 21:07
Simply get the user to put the port of the TS, not query port into the teamspeak.yml and use that value with selectVirtualServerByPort().

**Comment by Firedroide** [comment] 2015-09-05 21:09
![image](https://cloud.githubusercontent.com/assets/1472572/9701292/d31c0d6e-5422-11e5-9957-d002e8ab3f65.png)

Just looking at your page, it doesn't look like you're doing that ^^

You should not only let users set the host, but also both the query port and the voice port / the server ID. Both can be changed on a TS3 server.

Furthermore, I think it's bad practice to send your users to download the API here. Just use maven or configure your IDE to include our API in your .jar file. Saves the users time and reduces the risks of mishaps happening.

**Comment by Mauricius17** [comment] 2015-09-05 21:13
How can i set the voice port? I do not find any method with this option

**Comment by Firedroide** [comment] 2015-09-05 21:15
You need the voice port when you use `api.selectVirtualServerByPort`.

You can only use this command once you're connected to the TS3 server, for which you use the query port.

**Comment by Firedroide** [comment] 2015-09-05 21:17
What I mean by that is that each TS3 server instance has one query port for all virtual servers.

Each virtual server has both a unique ID and a unique voice port. If you want to select a virtual server, you can use either of the two.

**Comment by Mauricius17** [comment] 2015-09-05 21:25
Thank you:) Can you tell me how to create the jar includes the Teamspeak api? I just added the repo and the dependencies in my pom.xml but I have no idea how to include it while building the plugin:)

**Comment by Firedroide** [comment] 2015-09-05 21:27
Either use the [Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/usage.html) or the [Maven Assembly Plugin](https://maven.apache.org/plugins/maven-assembly-plugin/usage.html) to include dependencies in a "fat jar".

**Comment by Mauricius17** [comment] 2015-09-05 21:30
If I use the shade plugin and I added the stuff in my pom.xml how can I include dependencies in a "fat jar" ? I am a little bit confused

**Comment by Firedroide** [comment] 2015-09-05 21:32
Sorry, bad wording on my side. Including either the shade plugin in your lifecycle will create a second .jar file (besides the one that's already being created) with all dependencies included.

**Comment by Mauricius17** [comment] 2015-09-05 21:35
mhh can you show me an example please? A screenshot or somethink like this maybe? It would be helpful:)

**Comment by Firedroide** [comment] 2015-09-05 21:55
I literally just copy-pasted the example code from the usage pages.

https://gist.github.com/Firedroide/d1b7e185fef7c6cbfb2e

![image](https://cloud.githubusercontent.com/assets/1472572/9701442/a57b0084-5429-11e5-83ed-314386d844c5.png)

**Comment by Firedroide** [comment] 2015-09-05 21:58
Oh, and just as a side note, you probably don't even need 

```xml
<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
	<mainClass>Main</mainClass>
</transformer>
```

That's just if you want to make the whole thing executable. In your case (Bukkit plugin), that's not necessary.

**Comment by Mauricius17** [comment] 2015-09-05 22:16
@Firedroide  thank you:) But can you now tell me what I have to set on "Goals"! I have to add somethink there if I want to build it! http://prntscr.com/8d1kh1

**Comment by Firedroide** [comment] 2015-09-05 22:21
I'd go for `clean install`. That first deletes the "target" folder (clean), then compiles all your java files and all that stuff (everything from compile to package) and finally copies the artifacts over into your local maven repository at `%userprofile%/.m2` (install).

More info on the Maven lifecycle [here](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) and [here](https://maven.apache.org/ref/3.3.3/maven-core/lifecycles.html).

**Comment by Mauricius17** [comment] 2015-09-05 22:44
okay maybe I am stupid or what ever ... 

I got this http://hastebin.com/cicumoyore.tex error. Now I installed a new JDK! But the error is still there! What did I wrong?

**Comment by Firedroide** [comment] 2015-09-05 22:50
For almost every problem in computing, there's [a simple way to find answers](https://www.google.ch/search?btnG=1&pws=0&q=%22No+compiler+is+provided+in+this+environment.+Perhaps+you+are+running+on+a+JRE+rather+than+a+JDK%3F%22&gws_rd=cr,ssl&ei=NXHrVdOrC4Ssa6-JrIgB).

**Comment by Mauricius17** [comment] 2015-09-05 23:39
@Firedroide  I thank you a lot! If I have any questions in future I will ask you again:) Love you #NoHomo

**Comment by Firedroide** [comment] 2015-09-05 23:41
You're welcome! I hope, I wasn't too much of a douche. ^^
If any other questions arise, feel free to ask them here or over on [gitter, which is basically a chat room for a repository on GitHub](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API). :smile:

I'm gonna go ahead and close this issue now.

**Closed by Firedroide** 2015-09-05 23:41 UTC
